apiVersion: v1
kind: Pod
metadata: 
    name: startup-pod
    labels:
      env: dev
      app: prod
spec: 
    containers:
      - image: nginx
        name: startup-container
        ports:
          - containerPort: 80
            protocol: TCP
        startupProbe:
          httpGet: 
            path: /parvathi
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 4
        livenessProbe:
          exec: 
            command: 
              - tail -f var/log/nginx error.log 
              - touch gandru
        readinessProbe:
          tcpSocket:
            port: 80 


                


    